version: '3'
services:
  client:
    build: ../client
    ports:
      - "80:8080"
    depends_on:
      - server
    environment:
      - VUE_APP_HOST=localhost
  server:
    build: ../server
    ports:
      - "5000:5000"
